// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtlaolrvsdzkajnqrpon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0bGFvbHJ2c2R6a2FqbnFycG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTQ1OTksImV4cCI6MjA2MDk5MDU5OX0.aEzZhm5dB5el87nkwbxGBTmed5fI3f3SOjj1nI6YPRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);